version: "3.7"

services:
  nginx:
    image: nginx:1.14.0-alpine
    restart: unless-stopped
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 3000:80

  front:
    image: node:12.16.2
    restart: unless-stopped
    volumes:
      - ../front:/app
    working_dir: /app
    tty: true
    command: npm run start

  back:
    image: node:12.16.2
    restart: unless-stopped
    volumes:
      - ../back:/app
    working_dir: /app
    command: npm run start